# Generated by Django 4.2.16 on 2024-10-15 10:26

import asset_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetimage',
            options={'verbose_name_plural': 'Asset Images'},
        ),
        migrations.AlterModelOptions(
            name='assettype',
            options={'verbose_name_plural': 'Asset Types'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(default=asset_admin.models.get_uuid_digits, editable=False, max_length=16, unique=True, verbose_name='Asset Code'),
        ),
    ]
